/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131315",
        "canvas-pure-white": "#FFFFFF",
        "secondary-fixed": "#d3e4ff",
        "surface-tint": "#abc7ff",
        surface: "#131315",
        outline: "#8b919f",
        "on-primary": "#002f66",
        "on-secondary": "#00315b",
        tertiary: "#ffb783",
        "on-secondary-container": "#88b8f7",
        "canvas-dark": "#1D1D1F",
        "primary-fixed": "#d7e2ff",
        "outline-variant": "#414753",
        "on-tertiary-container": "#fffaf9",
        "surface-container-low": "#1b1b1d",
        "secondary-fixed-dim": "#a2c9ff",
        "inverse-surface": "#e4e2e4",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-container": "#a36536",
        "on-secondary-fixed-variant": "#054880",
        "surface-bright": "#39393b",
        "on-surface": "#e4e2e4",
        "on-surface-variant": "#c1c6d6",
        "on-tertiary-fixed-variant": "#6d390d",
        "on-primary-container": "#fcfbff",
        "on-tertiary": "#4f2500",
        "on-background": "#e4e2e4",
        error: "#ffb4ab",
        "secondary-container": "#054880",
        "canvas-light-gray": "#F5F5F7",
        "surface-container-highest": "#353437",
        "primary-container": "#0071e3",
        "text-secondary-dark": "#A1A1A6",
        "inverse-primary": "#005cbb",
        "surface-container": "#1f1f21",
        "surface-container-lowest": "#0e0e10",
        "border-light": "#E5E5EA",
        "on-tertiary-fixed": "#301400",
        "on-primary-fixed-variant": "#00458f",
        "surface-container-high": "#2a2a2c",
        "tertiary-fixed-dim": "#ffb783",
        background: "#131315",
        "text-muted-dark": "#86868B",
        "canvas-pure-black": "#000000",
        "primary-fixed-dim": "#abc7ff",
        secondary: "#a2c9ff",
        primary: "#abc7ff",
        "accent-electric-hover": "#0077ED",
        "text-muted-light": "#6E6E73",
        "on-error": "#690005",
        "canvas-card-dark": "#161617",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353437",
        "on-primary-fixed": "#001b3f",
        "on-secondary-fixed": "#001c38",
        "inverse-on-surface": "#303032",
        "border-dark": "#333336",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "section-hero": "8rem",
        "gutter-desktop": "2rem",
        "container-max": "75rem",
        "section-tight": "4rem",
        "section-regular": "6rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "3rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "display-xl": ["Inter"],
        "display-xl-mobile": ["Inter"],
        "title-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "title-lg": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg-mobile": ["34px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["40px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "84px", letterSpacing: "-0.035em", fontWeight: "700" }],
        "display-xl-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "title-md": ["19px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-lg": ["19px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "title-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-md-mobile": ["28px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
